# Generated by Django 5.1.6 on 2025-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
