# Generated by Django 5.1.6 on 2025-03-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
