# Generated by Django 5.1.6 on 2025-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
