# Generated by Django 5.1.6 on 2025-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0005_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
